import "./globals.css";
import NavBar from "./components/NavBar";
import Providers from "./providers";
import { Inter } from "next/font/google";
import { auth } from "@/auth";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

interface Props {
  children: React.ReactNode;
}

export default async function RootLayout({ children }: Props) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers session={session}>
          <div>
            <NavBar />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
