import "./globals.css";
import NavBar from "./components/NavBar";
import Providers from "./providers";
import AuthProvider from "./providers";
import { Inter } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

interface Props {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div>
            <NavBar />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
